name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            $HOME/.pub-cache
            $HOME/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Check Flutter Version
        run: flutter --version

      - name: Build APK
        run: flutter build apk --release

      - name: Check APK Existence
        id: check-apk
        run: |
          if [ -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "APK exists."
            echo "apk_exists=true" >> $GITHUB_OUTPUT
          else
            echo "APK does not exist."
            echo "apk_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload APK
        if: steps.check-apk.outputs.apk_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
